// pages/about/index.js
import Layout from '@/components/layout';
import Pricing from '@/components/pricing';
import Head from 'next/head';
import React from 'react';

const PricingPage = () => {
  return (
    <>
      <Head>
        <title>Pricing</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <Pricing />
      </Layout>
    </>
  );
};

export default PricingPage;
