// pages/about/index.js
import Layout from '@/components/layout';
import Pricing from '@/components/pricing';
import Head from 'next/head';
import React, { useEffect, useRef, useState } from 'react';

const PricingPage = () => {
  const myRef = useRef(null);
  const [isVisible, setIsVisible] = useState(false);
  useEffect(() => {
    const checkVisibility = () => {
      if (myRef.current) {
        const top = myRef.current.getBoundingClientRect().top;
        const windowHeight = window.innerHeight;

        if (top < windowHeight) {
          setIsVisible(true);
        } else {
          setIsVisible(false);
        }
      }
    };

    window.addEventListener('scroll', checkVisibility);
    checkVisibility();

    return () => {
      window.removeEventListener('scroll', checkVisibility);
    };
  }, []);
  return (
    <>
      <Head>
        <title>Pricing</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div ref={myRef}
          id="pricing"
          className={`  fade-in ${isVisible ? 'active' : ''}`}>
        <Layout>
        <Pricing />
      </Layout>
      </div>
      
    </>
  );
};

export default PricingPage;
